sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "001 - #221249 script.sql" -o  "D:\CP\Release\Script update\log.txt"

sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "003 - #227677 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "004 - #221251 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "005 - #222479 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "006 - #222939 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "007 - sp - MoveToNewMip.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "008 - #227675.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "009 - #228524 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "010 - #222937 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "012- #227896 [dbo].[SelectRiskMitigationControlsForFacilityClassAndSubClasses].sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "013 - #231906 script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "014 - sprint 6 - #221253.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "015 - sprint 6 - #230386.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "016 - sprint 6 - #230388.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "017 - sprint 6 - #231900.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "018 - sprint 7 - #222941 Create sp InsertMIPWithCodesFromSourceToDestinationPMRelease.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "019 - sprint 7 - #222941 execute Script.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "020 - sprint 7 - #222941 SelectMIPWithControlsInPMRelease2.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "021 - sprint 8 - #223423.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "022 - sprint 8 -  #223415 Missing Hazardous Materials Statements in Standard Activities .sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "023 - sprint 8 - #228568 GetXmlForSPOMIPReport.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "024 - sprint 8 - #228568 GetXmlForStandardActivityMaintenanceRequirement.sql" -o  "D:\CP\Release\Script update\log.txt"


sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "027 - sprint 9 - #237717 filter MIPs series by PMRelease.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "028 - sprint 9 - #237717 remove all duplicate MIPs series.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "029 - sprint 9 - #243733 Capabilities are being displayed multiple times.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "030 - sprint 9 - #239061 In Viewing mode of a completed analysis validity flag change.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "031 - sprint 10 - #232095 Ability to apply the same Standard Activity multiple times to same Installations.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "032 - sprint 10 - #237095 Cannot select previously rolledover releases in Initialisation process.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "033 - sprint 11 - #222941 InsertMissingMips.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "034 - sprint 12 - #261384 Need to add Ship name to display in Specification applications.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "035 - sprint 12 - #261388 Need to add Ship name to SA applied too selection Coordination.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "036 - sprint 12 - #261195 Additional USN to RAN rate conversion entries required.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "037 - sprint 12 - #239061 In Viewing mode of a completed analysis validity flag change.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "038 - sprint 12 - #261195 Additional USN to RAN rate conversion entries required.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "039 - sprint 13 - #266085 Add a new additional ASTM Resource Classification to ShipShape baseline.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "040 - sprint 13 - #259978 Transfer 3M Related Maintenance to FFGSPO MIP.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "041 - sprint 13 - #257508 Changes to MIP and SA pdf report presentations - #237669 - When Publishing all SA Freq appears to be from incorrect source.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "042 - sprint 14 - #265554 Date on the 3M MRC HTML view should reflect its USN MIP date.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "043 - sprint 14 - #223409 FFGSPO & AASSPO MPMI need to be rewritten for ShipShape 14.1.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "044 - sprint 15 - #271951 FR11-1 MIPs do not show in Consolidation-add-missing-components-ffg-11-fr-release.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "045 - sprint 15 - #271951 FR11-1 MIPs do not show in Consolidation-insert-missing-mips-1-to-ffg-11-fr-release.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "046 - sprint 15 - #271951 FR11-1 MIPs do not show in Consolidation-insert-missing-mips-2-to-ffg-11-fr-release.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "047 - sprint 15 - #258071 Loss of most MIP and MRC data in M2PS import into ShipShape - Create new stored procedure for M2PS report.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "048 - sprint 15 - #258071 Loss of most MIP and MRC data in M2PS import into ShipShape - Update stored procedure GetXmlForSPOMIPReport.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "049 - sprint 15 - #272044_Missing PM Analysis Rollover data and Validity after Initialisation process - SelectPMReleasesToBeRolledOver.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "050 - sprint 15 - #272044_Missing PM Analysis Rollover data and Validity after Initialisation process - SelectRiskMitigationControlsForFacilityClassAndSubClasses.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "051 - sprint 15 - #280625 Move 8 SAs for FFPD461Hxxx from MIP 4605004 to 4605100.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "052 - sprint 15 - #280631 Move SA for 3109 BU from 4840004 to 4840005.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "053 - sprint 16 - #225078 Cannot add comments to QC field correctly (ProjectStatus).sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "054 - sprint 16 - #258071 Loss of most MIP and MRC data in M2PS import into ShipShape #Update Present Periodicode.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "055 - sprint 16 - #258071 Loss of most MIP and MRC data in M2PS import into ShipShape #Update and insert in TriggerEvent and Resource Table.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "056 - sprint 16 - #272044_Missing PM Analysis Rollover data and Validity after Initialisation process -- confirmList.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "057 - sprint 16 - #271641 SA data for 3 MIPs being displayed in both the Requirements Controls to be Released.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "058 - sprint 17 - #286420 Change an invalid SA to valid when consolidated with a Valid MR.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "059 - sprint 17 - #280633 Hyperlink the SA numbers in Baseline Manager to the files.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "060 - sprint 17 - #280621 Periodicity now missing from HTML view and pdf report of SAs.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "061 - sprint 18 - #271949 New Conversion Rates displaing in Resourses.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "062 - sprint 18 - #272044 Missing PM Analysis Rollover data and Validity after Initialisation process.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "063 - sprint 18 - #272044 Missing PM Analysis Rollover data and Validity after Initialisation process - SelectRiskMitigationControlsForFacilityClassAndSubClasses.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "065 - sprint 19 - #275120 Move Standard Activities on MIP to display in another MIP table grouping.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "066 - sprint 19 - #272044 Missing PM Analysis Rollover data and Validity after Initialisation process.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "067 - sprint 19 - #286720 Extract Document Manager data tables for update - Update Document table data with Excel file.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "068 - sprint 19 - #286720 Extract Document Manager data tables for update - Update Document table column Pubdate relate xml data file.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "069 - sprint 20 - #282459 Not applied SAs still appearing in MIP Specification Controls.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "070 - sprint 20 - #292346 Move RANCE SAs to their correct MIP alignment.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "071 - sprint 20 - #291855 Move RANCE MRs to their correct MIP alignment with SAs.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "072 - sprint 20 - #280639 Display the MR Original 3M code to SAs if applied Risk Mitigation Controls.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "073 - sprint 20 - #284101 Improve Application of Installations for Equipment - add more capability filter.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "074 - sprint 20 - #284101 Improve Application of Installations for Equipment - Create Index in Facility.sql" -o  "D:\CP\Release\Script update\log.txt"
sqlcmd -S PXVINH\MSSQLSERVER2012 -E -i "075 - sprint 20 - #275120 Move Standard Activities on MIP to display in another MIP table grouping.sql" -o  "D:\CP\Release\Script update\log.txt"


PAUSE 